### ISSUE TITLE
No minimal working example / documentation

### ISSUE THREAD

**Issue by LRDPRDX** [Nabeel20/Badr#4]
Hi, @Nabeel20 

I don't know if it's only me, but I am a bit confused:

1) The example provided doesn't work -- the button does nothing. Yeah, I've seen that warning about the input binding, but I don't understand at all what you mean there. Ok. Let's go to the `badar.lua` file. I am expecting that uncommenting that part will fix the problem by providing kind of a default behaviour. But no, it doesn't work either.

2) I would like to know a bit more about your design: what those operators `+` and `-` are for ? Again, a working example would be nice.

I am looking forward to using your library and thank you for your work but now I cannot even understand the basics. Of course, If I dig deeper and read the whole code eventually I will definitely understand but I don't know now if it works at all. Am I missing something ?

**Comment by Nabeel20** [comment]
Hi, @LRDPRDX 

Thank you for your valuable feedback! I’ve updated the repo with additional documentation and a working example. This is my first open-source project, and I’m thrilled that you find it valuable. Please let me know if you encounter any further issues.

**Comment by LRDPRDX** [comment]
@Nabeel20 Thank you for your quick reply. Now it is much better :smile:
