### ISSUE TITLE
Removing a button or menu

### ISSUE THREAD

**Issue by mgussekloo** [Nabeel20/Badr#5]
Hi,

Thanks for the library! Is there an example for removing a component?

E.g. I have the following code:

local menu = component { column = true, gap = 10 }
	local button = button {
        text = 'Close menu',
        width = 200,
        onHover = function()
            print 'mouse entered'
            return function()
                print('mouse exited')
            end
        end,
        onClick = function(self)
        	-- what should I put here to remove the button and also restore the cursor?
-- and what should I put here to remove the menu entirely?
        end
    }
    menu = menu + button

**Comment by Nabeel20** [comment]
@mgussekloo Thanks! I hope this helps 😃. Feel free to ask any questions or share your feedback—it's always welcome!
```lua
onClick = function(self)
    -- remove button
    self.parent = self.parent - self
    -- restore cursor
    love.mouse.setCursor()
    -- "hide" the menu
    self.parent.visible = false
end
```
